// sdram_4port_sys.v

// Generated using ACDS version 20.1 711

`timescale 1 ps / 1 ps
module sdram_4port_sys (
		input  wire        clk_clk,                     //           clk.clk
		output wire        port1_cam_wr_waitrequest,    //  port1_cam_wr.waitrequest
		output wire [15:0] port1_cam_wr_readdata,       //              .readdata
		output wire        port1_cam_wr_readdatavalid,  //              .readdatavalid
		input  wire [0:0]  port1_cam_wr_burstcount,     //              .burstcount
		input  wire [15:0] port1_cam_wr_writedata,      //              .writedata
		input  wire [24:0] port1_cam_wr_address,        //              .address
		input  wire        port1_cam_wr_write,          //              .write
		input  wire        port1_cam_wr_read,           //              .read
		input  wire [1:0]  port1_cam_wr_byteenable,     //              .byteenable
		input  wire        port1_cam_wr_debugaccess,    //              .debugaccess
		output wire        port2_diff_wr_waitrequest,   // port2_diff_wr.waitrequest
		output wire [15:0] port2_diff_wr_readdata,      //              .readdata
		output wire        port2_diff_wr_readdatavalid, //              .readdatavalid
		input  wire [0:0]  port2_diff_wr_burstcount,    //              .burstcount
		input  wire [15:0] port2_diff_wr_writedata,     //              .writedata
		input  wire [24:0] port2_diff_wr_address,       //              .address
		input  wire        port2_diff_wr_write,         //              .write
		input  wire        port2_diff_wr_read,          //              .read
		input  wire [1:0]  port2_diff_wr_byteenable,    //              .byteenable
		input  wire        port2_diff_wr_debugaccess,   //              .debugaccess
		output wire        port3_diff_rd_waitrequest,   // port3_diff_rd.waitrequest
		output wire [15:0] port3_diff_rd_readdata,      //              .readdata
		output wire        port3_diff_rd_readdatavalid, //              .readdatavalid
		input  wire [0:0]  port3_diff_rd_burstcount,    //              .burstcount
		input  wire [15:0] port3_diff_rd_writedata,     //              .writedata
		input  wire [24:0] port3_diff_rd_address,       //              .address
		input  wire        port3_diff_rd_write,         //              .write
		input  wire        port3_diff_rd_read,          //              .read
		input  wire [1:0]  port3_diff_rd_byteenable,    //              .byteenable
		input  wire        port3_diff_rd_debugaccess,   //              .debugaccess
		output wire        port4_eth_rd_waitrequest,    //  port4_eth_rd.waitrequest
		output wire [15:0] port4_eth_rd_readdata,       //              .readdata
		output wire        port4_eth_rd_readdatavalid,  //              .readdatavalid
		input  wire [0:0]  port4_eth_rd_burstcount,     //              .burstcount
		input  wire [15:0] port4_eth_rd_writedata,      //              .writedata
		input  wire [24:0] port4_eth_rd_address,        //              .address
		input  wire        port4_eth_rd_write,          //              .write
		input  wire        port4_eth_rd_read,           //              .read
		input  wire [1:0]  port4_eth_rd_byteenable,     //              .byteenable
		input  wire        port4_eth_rd_debugaccess,    //              .debugaccess
		input  wire        reset_reset_n,               //         reset.reset_n
		output wire [12:0] sdram_wire_addr,             //    sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,               //              .ba
		output wire        sdram_wire_cas_n,            //              .cas_n
		output wire        sdram_wire_cke,              //              .cke
		output wire        sdram_wire_cs_n,             //              .cs_n
		inout  wire [15:0] sdram_wire_dq,               //              .dq
		output wire [1:0]  sdram_wire_dqm,              //              .dqm
		output wire        sdram_wire_ras_n,            //              .ras_n
		output wire        sdram_wire_we_n              //              .we_n
	);

	wire         mm_bridge_0_m0_waitrequest;                                // mm_interconnect_0:mm_bridge_0_m0_waitrequest -> mm_bridge_0:m0_waitrequest
	wire  [15:0] mm_bridge_0_m0_readdata;                                   // mm_interconnect_0:mm_bridge_0_m0_readdata -> mm_bridge_0:m0_readdata
	wire         mm_bridge_0_m0_debugaccess;                                // mm_bridge_0:m0_debugaccess -> mm_interconnect_0:mm_bridge_0_m0_debugaccess
	wire  [24:0] mm_bridge_0_m0_address;                                    // mm_bridge_0:m0_address -> mm_interconnect_0:mm_bridge_0_m0_address
	wire         mm_bridge_0_m0_read;                                       // mm_bridge_0:m0_read -> mm_interconnect_0:mm_bridge_0_m0_read
	wire   [1:0] mm_bridge_0_m0_byteenable;                                 // mm_bridge_0:m0_byteenable -> mm_interconnect_0:mm_bridge_0_m0_byteenable
	wire         mm_bridge_0_m0_readdatavalid;                              // mm_interconnect_0:mm_bridge_0_m0_readdatavalid -> mm_bridge_0:m0_readdatavalid
	wire  [15:0] mm_bridge_0_m0_writedata;                                  // mm_bridge_0:m0_writedata -> mm_interconnect_0:mm_bridge_0_m0_writedata
	wire         mm_bridge_0_m0_write;                                      // mm_bridge_0:m0_write -> mm_interconnect_0:mm_bridge_0_m0_write
	wire   [0:0] mm_bridge_0_m0_burstcount;                                 // mm_bridge_0:m0_burstcount -> mm_interconnect_0:mm_bridge_0_m0_burstcount
	wire         mm_bridge_1_m0_waitrequest;                                // mm_interconnect_0:mm_bridge_1_m0_waitrequest -> mm_bridge_1:m0_waitrequest
	wire  [15:0] mm_bridge_1_m0_readdata;                                   // mm_interconnect_0:mm_bridge_1_m0_readdata -> mm_bridge_1:m0_readdata
	wire         mm_bridge_1_m0_debugaccess;                                // mm_bridge_1:m0_debugaccess -> mm_interconnect_0:mm_bridge_1_m0_debugaccess
	wire  [24:0] mm_bridge_1_m0_address;                                    // mm_bridge_1:m0_address -> mm_interconnect_0:mm_bridge_1_m0_address
	wire         mm_bridge_1_m0_read;                                       // mm_bridge_1:m0_read -> mm_interconnect_0:mm_bridge_1_m0_read
	wire   [1:0] mm_bridge_1_m0_byteenable;                                 // mm_bridge_1:m0_byteenable -> mm_interconnect_0:mm_bridge_1_m0_byteenable
	wire         mm_bridge_1_m0_readdatavalid;                              // mm_interconnect_0:mm_bridge_1_m0_readdatavalid -> mm_bridge_1:m0_readdatavalid
	wire  [15:0] mm_bridge_1_m0_writedata;                                  // mm_bridge_1:m0_writedata -> mm_interconnect_0:mm_bridge_1_m0_writedata
	wire         mm_bridge_1_m0_write;                                      // mm_bridge_1:m0_write -> mm_interconnect_0:mm_bridge_1_m0_write
	wire   [0:0] mm_bridge_1_m0_burstcount;                                 // mm_bridge_1:m0_burstcount -> mm_interconnect_0:mm_bridge_1_m0_burstcount
	wire         mm_bridge_2_m0_waitrequest;                                // mm_interconnect_0:mm_bridge_2_m0_waitrequest -> mm_bridge_2:m0_waitrequest
	wire  [15:0] mm_bridge_2_m0_readdata;                                   // mm_interconnect_0:mm_bridge_2_m0_readdata -> mm_bridge_2:m0_readdata
	wire         mm_bridge_2_m0_debugaccess;                                // mm_bridge_2:m0_debugaccess -> mm_interconnect_0:mm_bridge_2_m0_debugaccess
	wire  [24:0] mm_bridge_2_m0_address;                                    // mm_bridge_2:m0_address -> mm_interconnect_0:mm_bridge_2_m0_address
	wire         mm_bridge_2_m0_read;                                       // mm_bridge_2:m0_read -> mm_interconnect_0:mm_bridge_2_m0_read
	wire   [1:0] mm_bridge_2_m0_byteenable;                                 // mm_bridge_2:m0_byteenable -> mm_interconnect_0:mm_bridge_2_m0_byteenable
	wire         mm_bridge_2_m0_readdatavalid;                              // mm_interconnect_0:mm_bridge_2_m0_readdatavalid -> mm_bridge_2:m0_readdatavalid
	wire  [15:0] mm_bridge_2_m0_writedata;                                  // mm_bridge_2:m0_writedata -> mm_interconnect_0:mm_bridge_2_m0_writedata
	wire         mm_bridge_2_m0_write;                                      // mm_bridge_2:m0_write -> mm_interconnect_0:mm_bridge_2_m0_write
	wire   [0:0] mm_bridge_2_m0_burstcount;                                 // mm_bridge_2:m0_burstcount -> mm_interconnect_0:mm_bridge_2_m0_burstcount
	wire         mm_bridge_3_m0_waitrequest;                                // mm_interconnect_0:mm_bridge_3_m0_waitrequest -> mm_bridge_3:m0_waitrequest
	wire  [15:0] mm_bridge_3_m0_readdata;                                   // mm_interconnect_0:mm_bridge_3_m0_readdata -> mm_bridge_3:m0_readdata
	wire         mm_bridge_3_m0_debugaccess;                                // mm_bridge_3:m0_debugaccess -> mm_interconnect_0:mm_bridge_3_m0_debugaccess
	wire  [24:0] mm_bridge_3_m0_address;                                    // mm_bridge_3:m0_address -> mm_interconnect_0:mm_bridge_3_m0_address
	wire         mm_bridge_3_m0_read;                                       // mm_bridge_3:m0_read -> mm_interconnect_0:mm_bridge_3_m0_read
	wire   [1:0] mm_bridge_3_m0_byteenable;                                 // mm_bridge_3:m0_byteenable -> mm_interconnect_0:mm_bridge_3_m0_byteenable
	wire         mm_bridge_3_m0_readdatavalid;                              // mm_interconnect_0:mm_bridge_3_m0_readdatavalid -> mm_bridge_3:m0_readdatavalid
	wire  [15:0] mm_bridge_3_m0_writedata;                                  // mm_bridge_3:m0_writedata -> mm_interconnect_0:mm_bridge_3_m0_writedata
	wire         mm_bridge_3_m0_write;                                      // mm_bridge_3:m0_write -> mm_interconnect_0:mm_bridge_3_m0_write
	wire   [0:0] mm_bridge_3_m0_burstcount;                                 // mm_bridge_3:m0_burstcount -> mm_interconnect_0:mm_bridge_3_m0_burstcount
	wire         mm_interconnect_0_new_sdram_controller_0_s1_chipselect;    // mm_interconnect_0:new_sdram_controller_0_s1_chipselect -> new_sdram_controller_0:az_cs
	wire  [15:0] mm_interconnect_0_new_sdram_controller_0_s1_readdata;      // new_sdram_controller_0:za_data -> mm_interconnect_0:new_sdram_controller_0_s1_readdata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_waitrequest;   // new_sdram_controller_0:za_waitrequest -> mm_interconnect_0:new_sdram_controller_0_s1_waitrequest
	wire  [23:0] mm_interconnect_0_new_sdram_controller_0_s1_address;       // mm_interconnect_0:new_sdram_controller_0_s1_address -> new_sdram_controller_0:az_addr
	wire         mm_interconnect_0_new_sdram_controller_0_s1_read;          // mm_interconnect_0:new_sdram_controller_0_s1_read -> new_sdram_controller_0:az_rd_n
	wire   [1:0] mm_interconnect_0_new_sdram_controller_0_s1_byteenable;    // mm_interconnect_0:new_sdram_controller_0_s1_byteenable -> new_sdram_controller_0:az_be_n
	wire         mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid; // new_sdram_controller_0:za_valid -> mm_interconnect_0:new_sdram_controller_0_s1_readdatavalid
	wire         mm_interconnect_0_new_sdram_controller_0_s1_write;         // mm_interconnect_0:new_sdram_controller_0_s1_write -> new_sdram_controller_0:az_wr_n
	wire  [15:0] mm_interconnect_0_new_sdram_controller_0_s1_writedata;     // mm_interconnect_0:new_sdram_controller_0_s1_writedata -> new_sdram_controller_0:az_data
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [mm_bridge_0:reset, mm_bridge_1:reset, mm_bridge_2:reset, mm_bridge_3:reset, mm_interconnect_0:mm_bridge_0_reset_reset_bridge_in_reset_reset, new_sdram_controller_0:reset_n]

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (25),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) mm_bridge_0 (
		.clk              (clk_clk),                        //   clk.clk
		.reset            (rst_controller_reset_out_reset), // reset.reset
		.s0_waitrequest   (port1_cam_wr_waitrequest),       //    s0.waitrequest
		.s0_readdata      (port1_cam_wr_readdata),          //      .readdata
		.s0_readdatavalid (port1_cam_wr_readdatavalid),     //      .readdatavalid
		.s0_burstcount    (port1_cam_wr_burstcount),        //      .burstcount
		.s0_writedata     (port1_cam_wr_writedata),         //      .writedata
		.s0_address       (port1_cam_wr_address),           //      .address
		.s0_write         (port1_cam_wr_write),             //      .write
		.s0_read          (port1_cam_wr_read),              //      .read
		.s0_byteenable    (port1_cam_wr_byteenable),        //      .byteenable
		.s0_debugaccess   (port1_cam_wr_debugaccess),       //      .debugaccess
		.m0_waitrequest   (mm_bridge_0_m0_waitrequest),     //    m0.waitrequest
		.m0_readdata      (mm_bridge_0_m0_readdata),        //      .readdata
		.m0_readdatavalid (mm_bridge_0_m0_readdatavalid),   //      .readdatavalid
		.m0_burstcount    (mm_bridge_0_m0_burstcount),      //      .burstcount
		.m0_writedata     (mm_bridge_0_m0_writedata),       //      .writedata
		.m0_address       (mm_bridge_0_m0_address),         //      .address
		.m0_write         (mm_bridge_0_m0_write),           //      .write
		.m0_read          (mm_bridge_0_m0_read),            //      .read
		.m0_byteenable    (mm_bridge_0_m0_byteenable),      //      .byteenable
		.m0_debugaccess   (mm_bridge_0_m0_debugaccess),     //      .debugaccess
		.s0_response      (),                               // (terminated)
		.m0_response      (2'b00)                           // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (25),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) mm_bridge_1 (
		.clk              (clk_clk),                        //   clk.clk
		.reset            (rst_controller_reset_out_reset), // reset.reset
		.s0_waitrequest   (port2_diff_wr_waitrequest),      //    s0.waitrequest
		.s0_readdata      (port2_diff_wr_readdata),         //      .readdata
		.s0_readdatavalid (port2_diff_wr_readdatavalid),    //      .readdatavalid
		.s0_burstcount    (port2_diff_wr_burstcount),       //      .burstcount
		.s0_writedata     (port2_diff_wr_writedata),        //      .writedata
		.s0_address       (port2_diff_wr_address),          //      .address
		.s0_write         (port2_diff_wr_write),            //      .write
		.s0_read          (port2_diff_wr_read),             //      .read
		.s0_byteenable    (port2_diff_wr_byteenable),       //      .byteenable
		.s0_debugaccess   (port2_diff_wr_debugaccess),      //      .debugaccess
		.m0_waitrequest   (mm_bridge_1_m0_waitrequest),     //    m0.waitrequest
		.m0_readdata      (mm_bridge_1_m0_readdata),        //      .readdata
		.m0_readdatavalid (mm_bridge_1_m0_readdatavalid),   //      .readdatavalid
		.m0_burstcount    (mm_bridge_1_m0_burstcount),      //      .burstcount
		.m0_writedata     (mm_bridge_1_m0_writedata),       //      .writedata
		.m0_address       (mm_bridge_1_m0_address),         //      .address
		.m0_write         (mm_bridge_1_m0_write),           //      .write
		.m0_read          (mm_bridge_1_m0_read),            //      .read
		.m0_byteenable    (mm_bridge_1_m0_byteenable),      //      .byteenable
		.m0_debugaccess   (mm_bridge_1_m0_debugaccess),     //      .debugaccess
		.s0_response      (),                               // (terminated)
		.m0_response      (2'b00)                           // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (25),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) mm_bridge_2 (
		.clk              (clk_clk),                        //   clk.clk
		.reset            (rst_controller_reset_out_reset), // reset.reset
		.s0_waitrequest   (port3_diff_rd_waitrequest),      //    s0.waitrequest
		.s0_readdata      (port3_diff_rd_readdata),         //      .readdata
		.s0_readdatavalid (port3_diff_rd_readdatavalid),    //      .readdatavalid
		.s0_burstcount    (port3_diff_rd_burstcount),       //      .burstcount
		.s0_writedata     (port3_diff_rd_writedata),        //      .writedata
		.s0_address       (port3_diff_rd_address),          //      .address
		.s0_write         (port3_diff_rd_write),            //      .write
		.s0_read          (port3_diff_rd_read),             //      .read
		.s0_byteenable    (port3_diff_rd_byteenable),       //      .byteenable
		.s0_debugaccess   (port3_diff_rd_debugaccess),      //      .debugaccess
		.m0_waitrequest   (mm_bridge_2_m0_waitrequest),     //    m0.waitrequest
		.m0_readdata      (mm_bridge_2_m0_readdata),        //      .readdata
		.m0_readdatavalid (mm_bridge_2_m0_readdatavalid),   //      .readdatavalid
		.m0_burstcount    (mm_bridge_2_m0_burstcount),      //      .burstcount
		.m0_writedata     (mm_bridge_2_m0_writedata),       //      .writedata
		.m0_address       (mm_bridge_2_m0_address),         //      .address
		.m0_write         (mm_bridge_2_m0_write),           //      .write
		.m0_read          (mm_bridge_2_m0_read),            //      .read
		.m0_byteenable    (mm_bridge_2_m0_byteenable),      //      .byteenable
		.m0_debugaccess   (mm_bridge_2_m0_debugaccess),     //      .debugaccess
		.s0_response      (),                               // (terminated)
		.m0_response      (2'b00)                           // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (25),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) mm_bridge_3 (
		.clk              (clk_clk),                        //   clk.clk
		.reset            (rst_controller_reset_out_reset), // reset.reset
		.s0_waitrequest   (port4_eth_rd_waitrequest),       //    s0.waitrequest
		.s0_readdata      (port4_eth_rd_readdata),          //      .readdata
		.s0_readdatavalid (port4_eth_rd_readdatavalid),     //      .readdatavalid
		.s0_burstcount    (port4_eth_rd_burstcount),        //      .burstcount
		.s0_writedata     (port4_eth_rd_writedata),         //      .writedata
		.s0_address       (port4_eth_rd_address),           //      .address
		.s0_write         (port4_eth_rd_write),             //      .write
		.s0_read          (port4_eth_rd_read),              //      .read
		.s0_byteenable    (port4_eth_rd_byteenable),        //      .byteenable
		.s0_debugaccess   (port4_eth_rd_debugaccess),       //      .debugaccess
		.m0_waitrequest   (mm_bridge_3_m0_waitrequest),     //    m0.waitrequest
		.m0_readdata      (mm_bridge_3_m0_readdata),        //      .readdata
		.m0_readdatavalid (mm_bridge_3_m0_readdatavalid),   //      .readdatavalid
		.m0_burstcount    (mm_bridge_3_m0_burstcount),      //      .burstcount
		.m0_writedata     (mm_bridge_3_m0_writedata),       //      .writedata
		.m0_address       (mm_bridge_3_m0_address),         //      .address
		.m0_write         (mm_bridge_3_m0_write),           //      .write
		.m0_read          (mm_bridge_3_m0_read),            //      .read
		.m0_byteenable    (mm_bridge_3_m0_byteenable),      //      .byteenable
		.m0_debugaccess   (mm_bridge_3_m0_debugaccess),     //      .debugaccess
		.s0_response      (),                               // (terminated)
		.m0_response      (2'b00)                           // (terminated)
	);

	sdram_4port_sys_new_sdram_controller_0 new_sdram_controller_0 (
		.clk            (clk_clk),                                                   //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),                           // reset.reset_n
		.az_addr        (mm_interconnect_0_new_sdram_controller_0_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_new_sdram_controller_0_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_new_sdram_controller_0_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_new_sdram_controller_0_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_new_sdram_controller_0_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                                           //  wire.export
		.zs_ba          (sdram_wire_ba),                                             //      .export
		.zs_cas_n       (sdram_wire_cas_n),                                          //      .export
		.zs_cke         (sdram_wire_cke),                                            //      .export
		.zs_cs_n        (sdram_wire_cs_n),                                           //      .export
		.zs_dq          (sdram_wire_dq),                                             //      .export
		.zs_dqm         (sdram_wire_dqm),                                            //      .export
		.zs_ras_n       (sdram_wire_ras_n),                                          //      .export
		.zs_we_n        (sdram_wire_we_n)                                            //      .export
	);

	sdram_4port_sys_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                 (clk_clk),                                                   //                               clk_0_clk.clk
		.mm_bridge_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                            // mm_bridge_0_reset_reset_bridge_in_reset.reset
		.mm_bridge_0_m0_address                        (mm_bridge_0_m0_address),                                    //                          mm_bridge_0_m0.address
		.mm_bridge_0_m0_waitrequest                    (mm_bridge_0_m0_waitrequest),                                //                                        .waitrequest
		.mm_bridge_0_m0_burstcount                     (mm_bridge_0_m0_burstcount),                                 //                                        .burstcount
		.mm_bridge_0_m0_byteenable                     (mm_bridge_0_m0_byteenable),                                 //                                        .byteenable
		.mm_bridge_0_m0_read                           (mm_bridge_0_m0_read),                                       //                                        .read
		.mm_bridge_0_m0_readdata                       (mm_bridge_0_m0_readdata),                                   //                                        .readdata
		.mm_bridge_0_m0_readdatavalid                  (mm_bridge_0_m0_readdatavalid),                              //                                        .readdatavalid
		.mm_bridge_0_m0_write                          (mm_bridge_0_m0_write),                                      //                                        .write
		.mm_bridge_0_m0_writedata                      (mm_bridge_0_m0_writedata),                                  //                                        .writedata
		.mm_bridge_0_m0_debugaccess                    (mm_bridge_0_m0_debugaccess),                                //                                        .debugaccess
		.mm_bridge_1_m0_address                        (mm_bridge_1_m0_address),                                    //                          mm_bridge_1_m0.address
		.mm_bridge_1_m0_waitrequest                    (mm_bridge_1_m0_waitrequest),                                //                                        .waitrequest
		.mm_bridge_1_m0_burstcount                     (mm_bridge_1_m0_burstcount),                                 //                                        .burstcount
		.mm_bridge_1_m0_byteenable                     (mm_bridge_1_m0_byteenable),                                 //                                        .byteenable
		.mm_bridge_1_m0_read                           (mm_bridge_1_m0_read),                                       //                                        .read
		.mm_bridge_1_m0_readdata                       (mm_bridge_1_m0_readdata),                                   //                                        .readdata
		.mm_bridge_1_m0_readdatavalid                  (mm_bridge_1_m0_readdatavalid),                              //                                        .readdatavalid
		.mm_bridge_1_m0_write                          (mm_bridge_1_m0_write),                                      //                                        .write
		.mm_bridge_1_m0_writedata                      (mm_bridge_1_m0_writedata),                                  //                                        .writedata
		.mm_bridge_1_m0_debugaccess                    (mm_bridge_1_m0_debugaccess),                                //                                        .debugaccess
		.mm_bridge_2_m0_address                        (mm_bridge_2_m0_address),                                    //                          mm_bridge_2_m0.address
		.mm_bridge_2_m0_waitrequest                    (mm_bridge_2_m0_waitrequest),                                //                                        .waitrequest
		.mm_bridge_2_m0_burstcount                     (mm_bridge_2_m0_burstcount),                                 //                                        .burstcount
		.mm_bridge_2_m0_byteenable                     (mm_bridge_2_m0_byteenable),                                 //                                        .byteenable
		.mm_bridge_2_m0_read                           (mm_bridge_2_m0_read),                                       //                                        .read
		.mm_bridge_2_m0_readdata                       (mm_bridge_2_m0_readdata),                                   //                                        .readdata
		.mm_bridge_2_m0_readdatavalid                  (mm_bridge_2_m0_readdatavalid),                              //                                        .readdatavalid
		.mm_bridge_2_m0_write                          (mm_bridge_2_m0_write),                                      //                                        .write
		.mm_bridge_2_m0_writedata                      (mm_bridge_2_m0_writedata),                                  //                                        .writedata
		.mm_bridge_2_m0_debugaccess                    (mm_bridge_2_m0_debugaccess),                                //                                        .debugaccess
		.mm_bridge_3_m0_address                        (mm_bridge_3_m0_address),                                    //                          mm_bridge_3_m0.address
		.mm_bridge_3_m0_waitrequest                    (mm_bridge_3_m0_waitrequest),                                //                                        .waitrequest
		.mm_bridge_3_m0_burstcount                     (mm_bridge_3_m0_burstcount),                                 //                                        .burstcount
		.mm_bridge_3_m0_byteenable                     (mm_bridge_3_m0_byteenable),                                 //                                        .byteenable
		.mm_bridge_3_m0_read                           (mm_bridge_3_m0_read),                                       //                                        .read
		.mm_bridge_3_m0_readdata                       (mm_bridge_3_m0_readdata),                                   //                                        .readdata
		.mm_bridge_3_m0_readdatavalid                  (mm_bridge_3_m0_readdatavalid),                              //                                        .readdatavalid
		.mm_bridge_3_m0_write                          (mm_bridge_3_m0_write),                                      //                                        .write
		.mm_bridge_3_m0_writedata                      (mm_bridge_3_m0_writedata),                                  //                                        .writedata
		.mm_bridge_3_m0_debugaccess                    (mm_bridge_3_m0_debugaccess),                                //                                        .debugaccess
		.new_sdram_controller_0_s1_address             (mm_interconnect_0_new_sdram_controller_0_s1_address),       //               new_sdram_controller_0_s1.address
		.new_sdram_controller_0_s1_write               (mm_interconnect_0_new_sdram_controller_0_s1_write),         //                                        .write
		.new_sdram_controller_0_s1_read                (mm_interconnect_0_new_sdram_controller_0_s1_read),          //                                        .read
		.new_sdram_controller_0_s1_readdata            (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //                                        .readdata
		.new_sdram_controller_0_s1_writedata           (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //                                        .writedata
		.new_sdram_controller_0_s1_byteenable          (mm_interconnect_0_new_sdram_controller_0_s1_byteenable),    //                                        .byteenable
		.new_sdram_controller_0_s1_readdatavalid       (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //                                        .readdatavalid
		.new_sdram_controller_0_s1_waitrequest         (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //                                        .waitrequest
		.new_sdram_controller_0_s1_chipselect          (mm_interconnect_0_new_sdram_controller_0_s1_chipselect)     //                                        .chipselect
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
