	sdram_4port_sys u0 (
		.clk_clk                     (<connected-to-clk_clk>),                     //           clk.clk
		.reset_reset_n               (<connected-to-reset_reset_n>),               //         reset.reset_n
		.sdram_wire_addr             (<connected-to-sdram_wire_addr>),             //    sdram_wire.addr
		.sdram_wire_ba               (<connected-to-sdram_wire_ba>),               //              .ba
		.sdram_wire_cas_n            (<connected-to-sdram_wire_cas_n>),            //              .cas_n
		.sdram_wire_cke              (<connected-to-sdram_wire_cke>),              //              .cke
		.sdram_wire_cs_n             (<connected-to-sdram_wire_cs_n>),             //              .cs_n
		.sdram_wire_dq               (<connected-to-sdram_wire_dq>),               //              .dq
		.sdram_wire_dqm              (<connected-to-sdram_wire_dqm>),              //              .dqm
		.sdram_wire_ras_n            (<connected-to-sdram_wire_ras_n>),            //              .ras_n
		.sdram_wire_we_n             (<connected-to-sdram_wire_we_n>),             //              .we_n
		.port1_cam_wr_waitrequest    (<connected-to-port1_cam_wr_waitrequest>),    //  port1_cam_wr.waitrequest
		.port1_cam_wr_readdata       (<connected-to-port1_cam_wr_readdata>),       //              .readdata
		.port1_cam_wr_readdatavalid  (<connected-to-port1_cam_wr_readdatavalid>),  //              .readdatavalid
		.port1_cam_wr_burstcount     (<connected-to-port1_cam_wr_burstcount>),     //              .burstcount
		.port1_cam_wr_writedata      (<connected-to-port1_cam_wr_writedata>),      //              .writedata
		.port1_cam_wr_address        (<connected-to-port1_cam_wr_address>),        //              .address
		.port1_cam_wr_write          (<connected-to-port1_cam_wr_write>),          //              .write
		.port1_cam_wr_read           (<connected-to-port1_cam_wr_read>),           //              .read
		.port1_cam_wr_byteenable     (<connected-to-port1_cam_wr_byteenable>),     //              .byteenable
		.port1_cam_wr_debugaccess    (<connected-to-port1_cam_wr_debugaccess>),    //              .debugaccess
		.port2_diff_wr_waitrequest   (<connected-to-port2_diff_wr_waitrequest>),   // port2_diff_wr.waitrequest
		.port2_diff_wr_readdata      (<connected-to-port2_diff_wr_readdata>),      //              .readdata
		.port2_diff_wr_readdatavalid (<connected-to-port2_diff_wr_readdatavalid>), //              .readdatavalid
		.port2_diff_wr_burstcount    (<connected-to-port2_diff_wr_burstcount>),    //              .burstcount
		.port2_diff_wr_writedata     (<connected-to-port2_diff_wr_writedata>),     //              .writedata
		.port2_diff_wr_address       (<connected-to-port2_diff_wr_address>),       //              .address
		.port2_diff_wr_write         (<connected-to-port2_diff_wr_write>),         //              .write
		.port2_diff_wr_read          (<connected-to-port2_diff_wr_read>),          //              .read
		.port2_diff_wr_byteenable    (<connected-to-port2_diff_wr_byteenable>),    //              .byteenable
		.port2_diff_wr_debugaccess   (<connected-to-port2_diff_wr_debugaccess>),   //              .debugaccess
		.port3_diff_rd_waitrequest   (<connected-to-port3_diff_rd_waitrequest>),   // port3_diff_rd.waitrequest
		.port3_diff_rd_readdata      (<connected-to-port3_diff_rd_readdata>),      //              .readdata
		.port3_diff_rd_readdatavalid (<connected-to-port3_diff_rd_readdatavalid>), //              .readdatavalid
		.port3_diff_rd_burstcount    (<connected-to-port3_diff_rd_burstcount>),    //              .burstcount
		.port3_diff_rd_writedata     (<connected-to-port3_diff_rd_writedata>),     //              .writedata
		.port3_diff_rd_address       (<connected-to-port3_diff_rd_address>),       //              .address
		.port3_diff_rd_write         (<connected-to-port3_diff_rd_write>),         //              .write
		.port3_diff_rd_read          (<connected-to-port3_diff_rd_read>),          //              .read
		.port3_diff_rd_byteenable    (<connected-to-port3_diff_rd_byteenable>),    //              .byteenable
		.port3_diff_rd_debugaccess   (<connected-to-port3_diff_rd_debugaccess>),   //              .debugaccess
		.port4_eth_rd_waitrequest    (<connected-to-port4_eth_rd_waitrequest>),    //  port4_eth_rd.waitrequest
		.port4_eth_rd_readdata       (<connected-to-port4_eth_rd_readdata>),       //              .readdata
		.port4_eth_rd_readdatavalid  (<connected-to-port4_eth_rd_readdatavalid>),  //              .readdatavalid
		.port4_eth_rd_burstcount     (<connected-to-port4_eth_rd_burstcount>),     //              .burstcount
		.port4_eth_rd_writedata      (<connected-to-port4_eth_rd_writedata>),      //              .writedata
		.port4_eth_rd_address        (<connected-to-port4_eth_rd_address>),        //              .address
		.port4_eth_rd_write          (<connected-to-port4_eth_rd_write>),          //              .write
		.port4_eth_rd_read           (<connected-to-port4_eth_rd_read>),           //              .read
		.port4_eth_rd_byteenable     (<connected-to-port4_eth_rd_byteenable>),     //              .byteenable
		.port4_eth_rd_debugaccess    (<connected-to-port4_eth_rd_debugaccess>)     //              .debugaccess
	);

